### ISSUE TITLE
SEP data workflow: Italian Air Pollution datasets

### ISSUE THREAD

**Issue by pafrance** [INTERSTAT/Statistics-Contextualized#18]
**Data extraction**
Step1: [data source website](https://annuario.isprambiente.it/sys_ind/448) 
Step2: Select DATA panel. Data are organized in a set of tables  
Step3: Scroll to the requested table, named “Tabella 1 – PM10. Stazioni di monitoraggio: dati e parametri statistici per la valutazione della qualità dell'aria (2019)”  
Step4: [Download link](https://annuario.isprambiente.it/sites/default/files/sys_ind_files/indicatori_ada/448/TABELLA%201_PM10_2019_rev.xlsx) available on the left bottom at the end of the table . Downloaded data are in xls format
The downloaded file is not compliant with the required Data Structure.

**Data transformation**
The downloaded file has the following Data Structure:
“Regione”,”Provincia”,”Comune”,”Nome della stazione	Tipo di zona”,”Tipo di stazione”,”Giorni di superamento di 50 µg/m3”,”Valore medio annuo³ [µg/m³]”,”Rendimento [%]”,”Rispetta copertura minima”,”sufficiente distribuzione temporale nell'anno”,”numero_dati_validi”,”TIPO DI DATI 4”,”Codice zona”,”Nome zona”
1.	Data need to be filtered in order to be compliant to the requested [Data Structure](https://github.com/smart-data-models/dataModel.Environment/blob/master/AirQualityObserved/doc/spec.md),
2.	NUTS3 variable has been added through a transformation from municipality_id Variable, using data from [ISTAT LAU archive](https://interstat.opsi-lab.it/graphdb/orefine/project?project=2607709777724&ui=%7B%22facets%22%3A%5B%5D%7D)
3.	Provided metadata for NUTS3 transformation need to be downloaded and merged. 	
Metadata are referenced in a time series and Variable regarding year 2019 has been used in the script.
4.	Metadata regarding pollutant type, data reference time and aggregation type have been added in the datafile.

**Data Load**
The transformed file has been uploaded into INTERSTAT GraphDB repository sep-test 
GraphDB allows direct link to the resources by a [permalink](https://interstat.opsi-lab.it/graphdb/orefine/project?project=2170315808821&ui=%7B%22facets%22%3A%5B%5D%7D), but the raw data needs a little reworking to be accessed directly.

**Further data files available** 
Same procedure can be used to import other data from Data Source Website
AMBIENT AIR QUALITY: NITROGEN DIOXIDE [NO2](https://annuario.isprambiente.it/sys_ind/450)
AMBIENT AIR QUALITY: TROPOSPHERIC OZONE [O3](https://annuario.isprambiente.it/sys_ind/451)
AMBIENT AIR QUALITY: PARTICULATE [PM2.5](https://annuario.isprambiente.it/sys_ind/452)
_These files have not been uploaded to GraphDB repository yet_

Transformation script in R language
[processing_ETL_AIR.R.txt](https://github.com/INTERSTAT/Statistics-Contextualized/files/7597210/processing_ETL_AIR.R.txt)

**Comment by francescadag** [comment]
The Italian Air Pollution dataset concerning PM 10 is available on the [FTP area of the project](https://interstat.opsi-lab.it/files/TABELLA-1_PM10_2019-csv.csv).

**Comment by pafrance** [comment]
French Data are available from [European Environmental Agency](http://aidef.apps.eea.europa.eu/?source=%7B%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%2C%22display_type%22%3A%22tabular%22%7D).
We downloaded a sample of data (PM10) now available on the [ftp area of the project](https://interstat.opsi-lab.it/files/data_PM10_France-csv.csv).
Please, we need a confirmation wether we got the right datasets or not.

The source data model is consistent with respect to both the Italian and French data except for the data conversion of geo spatial coordinates to administrative units.
But the [target data model](https://github.com/smart-data-models/dataModel.Environment/blob/master/AirQualityObserved/doc/spec.md) used for context broker ingestion is not compatible, as it is used for smart data models. 
We would like to explore this issue separately ([Issue 21](https://github.com/INTERSTAT/Statistics-Contextualized/issues/21))
I would like to leave this issue for data preparation and integration, because dataset can be integrated as they are, but if we consider smart model, there's a need to extract and convert data to the target model, adding a step in the process.

**Comment by francescadag** [comment]
The French dataset about the PM10 mentioned in the [previous post](https://github.com/INTERSTAT/Statistics-Contextualized/issues/18#issuecomment-1013043291) and which was uploaded to the [FTP server](https://interstat.opsi-lab.it/files/data_PM10_France-csv.csv) in its initial version contains the geographic coordinates; it has been enriched with the Municipality value through a script in java using the specific [service/API](https://nominatim.org/release-docs/develop/api/Reverse/).
The file obtained is available on the [FTP area of the project](https://interstat.opsi-lab.it/files/data_PM10_France-Municipality.csv).
After receiving the confirmation that the extrapolated French dataset is correct, in the same way we will extrapolate also the datasets of the other pollutants and I will also add to them the field that refers to the Municipality.
